### ISSUE TITLE
Fails to report statistical data on Android (400 Bad request)

### ISSUE THREAD

**Issue by durandt** [Microsoft/ApplicationInsights-Xamarin#11]
Hi, 

Today I gave yet another chance to Application Insights and got the following debug log when the SDK tries to send telemetry to Azure on an Android Xamarin.Forms application: 

```
[com.microsoft.applicationinsights.logging Sender] Logging payload:[{"ver":1,"name":"Microsoft.ApplicationInsights.PageView","time":"2015-10-07T13:55:34.846Z",...}]
[com.microsoft.applicationinsights.logging Sender] response code:400
[com.microsoft.applicationinsights.logging Persistence] Successfully deleted telemetry file :/data/data/com.my.domain.my.app/files/com.microsoft.applicationinsights/regularpriority/49d7d644-7ddf-4c3d-952b-64e79336cc83
[com.microsoft.applicationinsights.logging Sender] Unexpected response code: 400
```

And no statistics appear in the Application Insight dashboard in Azure's portal. 

I'd be thankful to know if someone is working on these issues (this one and issue #9) or if I should turn myself toward other products. 

Regards,

Thibault D.

**Comment by ghost** [comment]
Can you please use fiddler to get the response message? 

Thank you,

Christoph

**Comment by durandt** [comment]
Hi, 

Maybe I should have specified my configuration: 
I am using Xamarin Studio 5.9.7 on Mac OS 10.10.5
I use the feature/change-pcl-profile branch. 

I have installed fiddler in my local Windows VM and tried to configure both my computer and the Android emulator to use the proxy. My mac's traffic would go through fiddler's proxy but the Android emulator would ignore the settings. 

Anyway, I have not changed anything since yesterday and now the debug logs say that Application Insight backend answers "200 OK" and I can see the statistics in Azure's portal. 

Maybe it could have something to do with freshly created Insights projects in the portal?
I can't help you much more than with the timestamp of the data that was sent (2015-10-07T13:55:34.846Z), which should be a few seconds before the message was actually sent. But I could reproduce the issue several times yesterday. 

Regards,

**Comment by ghost** [comment]
Hi,

thanks for the information.

I guess the answer to this question is inside the response. That's really the first step of getting an idea, why this happens. Just use fiddler again the next time you come across the problem. Unfortunately, I'm not able to reproduce this one. But I keep trying for now.

Thank you

**Comment by durandt** [comment]
Ok thank you. 

I consider the issue fixed and I will keep an eye on the logs to see if it ever happens again. 

Regards,
