### ISSUE TITLE
Are Xamarin.Forms PCL projects supported?

### ISSUE THREAD

**Issue by gc435** [Microsoft/ApplicationInsights-Xamarin#13]
When trying to add AI to a Xamarin.Forms PCL project, I get:

```
Adding Microsoft.ApplicationInsights.Xamarin...
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.4.3.6374)'.
Adding 'Microsoft.ApplicationInsights.Xamarin 1.0.0-alpha2' to XFStreamingAudio.
Could not install package 'Microsoft.ApplicationInsights.Xamarin 1.0.0-alpha2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

My Xamarin.Forms PCL targets profile 78.

Does this SDK work with PCLs?

**Comment by ghost** [comment]
Hi, can you please switch to our develop branch at https://github.com/Microsoft/ApplicationInsights-Xamarin/tree/develop and give it another try?

From: gc435
Reply-To: Microsoft/ApplicationInsights-Xamarin
Date: Tuesday 3 November 2015 at 16:29
To: Microsoft/ApplicationInsights-Xamarin
Subject: [ApplicationInsights-Xamarin] Are Xamarin.Forms PCL projects supported? (#13)

When trying to add AI to a Xamarin.Forms PCL project, I get:

Adding Microsoft.ApplicationInsights.Xamarin...
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.4.3.6374)'.
Adding 'Microsoft.ApplicationInsights.Xamarin 1.0.0-alpha2' to XFStreamingAudio.
Could not install package 'Microsoft.ApplicationInsights.Xamarin 1.0.0-alpha2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My Xamarin.Forms PCL targets profile 78.

Does this SDK work with PCLs?

**Comment by gc435** [comment]
I retried with the develop branch, and get the same error.  I checked `git log` and have this commit as HEAD: 15707a9d9914a075f06aadfcfa8f4177480226e9.  I assume that's the commit you wanted me to try.

**Comment by gc435** [comment]
Here's the md5 of the package:

```
MD5 (Microsoft.ApplicationInsights.Xamarin.1.0.0-alpha2.nupkg) = 7c1703a7fd04599078d4692b25a4e360
```

**Comment by gc435** [comment]
Curiously, I can add AI to a new Xamarin.Forms app, but not one I've already been working on.  Both use Profile 78.

**Comment by gc435** [comment]
OK, I figured it out.  I had the package from the _master_ branch installed in my iOS project.  I didn't think that would affect packages added to my PCL.  However, I removed the old package from the iOS project and now I can add the _develop_ branch package to the PCL.
