### ISSUE TITLE
Duplicate PageView events on iOS

### ISSUE THREAD

**Issue by has-taiar** [Microsoft/ApplicationInsights-Xamarin#17]
I have downloaded and started using this sdk. 
I am getting duplicate events for PageView events in the portal. I started looking at the raw data (as I export it to Azure Table Storage), I could see that the SDK is sending the same page view events twice for each event. 

Any idea of what is happening? Your help would be highly appreciated.

**Comment by lumaxis** [comment]
Hey @has-taiar,
do you see the _exact same_ page views? It's known issue that `UIViewController`s with nested child view controllers might send duplicate-looking PageView events.

**Comment by has-taiar** [comment]
Thanks for the quick response @lumaxis, 
I found that there was an issue in my code :) 
Sorry false alarm :) so I am going to close this issue then
