### ISSUE TITLE
ApplicationInsights is not working in Xamarin.iOS App

### ISSUE THREAD

**Issue by jamesmundy** [Microsoft/ApplicationInsights-Xamarin#18]
Hi,

I'm really rather confused how I can get this library working in a Xamarin.iOS (not forms) app. I've tried several things with no luck on every branch here.

I am currently on the branch "Xamarin (1.0-alpha.3)" where the dependency on Xamarin.Forms was removed (I realise this hasn't been thoroughly tested). However, I am unable to follow the instructions in the Readme as CrossApplicationInsights does not exist in the namespace AI.XamarinSDK.

I have also tried following the instructions on the Master branch but that uses AI.XamarinSDK.Abstractions which causes a runtime error saying Xamarin.Forms isn't referenced.

Another thing I've also tried is referencing like this AI.XamarinSDK.iOS.MSAIApplicationInsights.Setup("******"); but that crashes silently at runtime with no exception.

Any pointers as to where I'm going wrong would be appreciated.

James

**Comment by ghost** [comment]
Hi James,

thanks for reporting. Can you probably provide me with your project? Feel free to strip away everything which is not necessary to reproduce this issue.

Thank you

**Comment by jamesmundy** [comment]
Thanks for getting back to me Christoph, I managed to get some code working using [this fork](https://github.com/has-taiar/Azure.ApplicationInsight.Xamarin) and a .dll I built but obviously I'd quite like to use your NuGet package. With the fork I used the following code:

```
  AI.Xamarin.iOS.ApplicationInsights.Init();
  var ai = new AI.Xamarin.iOS.ApplicationInsights();
  ApplicationInsights.Init(ai);

  TelemetryManager.Init(new AI.Xamarin.iOS.TelemetryManager());
  ApplicationInsights.Setup("507f15ec-132d-47e8-8c89-31fdd3ec746a");
  ApplicationInsights.Start();`
```

Following the instructions on the feature branch and using 1.0.0.0-alpha3 nuget I wrote this:

```
 CrossApplicationInsights.Current.Setup("<YOUR_IKEY_HERE>");
  CrossApplicationInsights.Current.Start();
  ApplicationInsights.SetDebugLogEnabled(false);`
```

Unfortunately this doesn't compile as none of these exist in the correct namespaces. Please find the link to my stripped down solution here: https://www.dropbox.com/sh/9vtu67km9rm35s9/AADCg2t1MVx-e2dRp46qBAsxa?dl=0

Hope this helps diagnose the issue (or maybe I've missed something)

**Comment by grahampett** [comment]
It looks to me like the alpha3 nuget on this branch contains the wrong version of the DLLs. I built the project manually and added direct references to the DLLs and it works fine.

Note that several of the projects still contain package references to Xamarin Forms, which I removed before building.

**Comment by jamesmundy** [comment]
I thought this might have been the case but still thought I would flag up anyway - unfortunately I haven't got a great deal of experience building NuGet packages so wasn't able to rebuild the package myself.

**Comment by ghost** [comment]
We are still testing. There seems to be an issue with using this branch in a Xamarin.Forms application while it's working well in iOS/Android projects. For now, please use the sources rather than the NuGet package. I'm going to get back to you once we verified, that this is still working together with Xamarin.Forms.

Thank you

**Comment by ghost** [comment]
@jamesmundy: Unfortunately we decided to deprecate this SDK. However I've updated the nuspec on master. I hope this might give you an idea how to pack the SDK. For the future, I higly recommend using the HockeySDK for Xamarin, which can be found [here](https://components.xamarin.com/view/hockeyappios).
