### ISSUE TITLE
Use Application Insights without Xamarin Forms

### ISSUE THREAD

**Issue by dominik-weber** [Microsoft/ApplicationInsights-Xamarin#2]
Hi,
I wanted to use Application Insights in an iOS project without Xamarin Forms. It seems like this is currently not possible, is there a valid workaround?

**Comment by ghost** [comment]
We are currently working on that. This is going to be part of the Alpha 3 release.

**Comment by angelocarlotto** [comment]
I´m trying to use Applications INsigths in an Xamarin.Android Project but i´m getting this exception:

```
You MUST call Xamarin.Forms.Init(); prior to using it.
```

When i run this line (OnStart) in the Main Activity:

```
ApplicationInsights.Setup ("999999-99999-999999-99999-9999");
```

Here is the version used in the project:

```
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="21" />
```

I´m using Xamarin Studio 5.9.4

Any ideia?

Guys, thanks a lot for this project.

**Comment by ghost** [comment]
For now just add `Xamarin.Forms.Forms.Init();`before calling `ApplicationInsights.Setup()`. We are currently working on a version, which does not need the Xamarin.Forms dependency.

**Comment by angelocarlotto** [comment]
First, thanks so much for the attention.

In this method

```
Xamarin.Forms.Forms.Init(Activity,Bundle);
```

I have to pass two args, any sugestions about the bundle?

**Comment by angelocarlotto** [comment]
No i´m facing a trouble with this code, when i call Setup: the variable target is null

```
        public static void Setup (string instrumentationKey)
        {
            target.Setup (instrumentationKey);
        }

```

**Comment by ghost** [comment]
The args should be `Xamarin.Forms.Forms.Init(this,bundle);`. Can you please check your linker settings in the project options? If the linker behaviour is not set to "Don't link", then the linker may strip away the assembly. If so, we need to provide a way to prevent the assembly from being stripped away.

**Comment by angelocarlotto** [comment]
The linker is just like you sad: "Don´t link"

But about the arg bundle, on the OnStart event i dont have access to no bundle variable:

```
protected override void OnStart ()
        {
            Xamarin.Forms.Forms.Init(this,????);
            ApplicationInsights.Setup ("9999-999-99-99999996-9999999");
            ApplicationInsights.Start ();
            ApplicationInsights.SetDebugLogEnabled(false);
        }
```

**Comment by angelocarlotto** [comment]
This line i dont get anymore exception

```
 Xamarin.Forms.Forms.Init(this,null);
```

But int this line:

```
ApplicationInsights.Setup ("9999-999-99-99999996-9999999");
```

I get, inside the Setup method, there is a variable called "target" witch is null. And cause a NullPointException

**Comment by ghost** [comment]
Please put the following code into the MainActivity.cs of your android platform project after adding the SDK NuGet:

```
using System;
using Android.App;
using Android.Content;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using AI.XamarinSDK.Abstractions;

namespace TestApp
{
    [Activity (Label = "TestApp", MainLauncher = true, Icon = "@drawable/icon")]
    public class MainActivity : Activity
    {

        protected override void OnCreate (Bundle bundle)
        {
            base.OnCreate (bundle);

            // Set our view from the "main" layout resource
            SetContentView (Resource.Layout.Main);

            Xamarin.Forms.Forms.Init (this, bundle);
            ApplicationInsights.Setup ("<INSTRUMENTATION_KEY");
            ApplicationInsights.Start ();
        }
    }
}
```

Edit the namespace and label text to fit your needs.

Cheers

**Comment by angelocarlotto** [comment]
Thanks, man.
Also i was forgetting to add a reference to

```
AI.XamarinSDK.Android;
```

Cheers

**Comment by ghost** [comment]
I'm going to get back to you once the Xamarin.Forms dependency has been removed.

Thank you

**Comment by dominik-weber** [comment]
@chrwend do you have any updates on this issue?

**Comment by Cheesebaron** [comment]
![http://cdn.meme.am/instances/65515111.jpg](http://cdn.meme.am/instances/65515111.jpg)

**Comment by xvare** [comment]
I commit a pull request for remove Xamarin Forms reference. See my branch if you want it.

**Comment by ghost** [comment]
Hi,

Thank you for the pull request. The team is already evaluating this one. I’m going to get back to you, once the PR has been merged.

Best,

Christoph

From: xvare
Reply-To: Microsoft/ApplicationInsights-Xamarin
Date: Tuesday 1 December 2015 at 07:08
To: Microsoft/ApplicationInsights-Xamarin
Cc: Christoph Wendt
Subject: Re: [ApplicationInsights-Xamarin] Use Application Insights without Xamarin Forms (#2)

I commit a pull request for remove Xamarin Forms reference. See my branch if you want it.
