### ISSUE TITLE
How do I build?

### ISSUE THREAD

**Issue by jmichas** [Microsoft/ApplicationInsights-Xamarin#20]
So, I got the feature zip with no forms dependency and I'm trying to build it.
I get this when trying to build the iOS version:

```
1>X:\ApplicationInsightsXamarinSDK\ApplicationInsightsXamarin\AI.XamarinSDK.iOS\TelemetryManager.cs(11,34,11,51): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>X:\ApplicationInsightsXamarinSDK\ApplicationInsightsXamarin\AI.XamarinSDK.iOS\TelemetryManager.cs(11,34,11,51): error CS0012: The type 'Exception' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

And the Android version give me this:

```
1>X:\ApplicationInsightsXamarinSDK\ApplicationInsightsXamarin\AI.XamarinSDK.Android\TelemetryManager.cs(7,21,7,40): error CS0234: The type or namespace name 'Applicationinsights' does not exist in the namespace 'Com.Microsoft' (are you missing an assembly reference?)
```

How do I fix these so I can build?

Thanks.

**Comment by jamesmundy** [comment]
For the iOS issues have you tried adding those missing assemblies as references in your project?

**Comment by jmichas** [comment]
Where are those dll's? I can't find them and I thought the Collections.Generic was in the System.dll. Am I wrong?

**Comment by jmichas** [comment]
Wait, so, System.Collections is in the mscorlib.dll, you can't add that manually because VS says that mscorlib is referenced automatically. So, not sure what to do. Nobody else has had this problem? Try downloading the zip of the code and open it and try and build, see if you get the same errors.

**Comment by sfinn-qci** [comment]
I have also been having problems getting the source to build for iOS.

Specifically, the AI.XamarinSK.iOS is not able to build for me with the following errors:

'Xamarin.Forms.DependencyAttribute' is not an attribute class - In both the TelemetryManager.cs and ApplicationInsights.cs

The type 'System.Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

For the second error, I have tried changing out the references, but have not been able to find a solution.  I am assuming the first error is related to this second error that I am receiving.  Any assistance on this issue would be much appreciated.

Thanks

**Comment by sfinn-qci** [comment]
FYI I was able to get the NuGet package into my existing app, and everything seems to be working well  in there.

**Comment by jmichas** [comment]
@sfinn-qci How did you get the NuGet package?
@chrwend Why was this closed? It is still not possible to build the source. 

Has anyone tried to download a zip of the source and build it? I was hoping to find out whether it is some quirk on my local dev machine or if it is a problem for anyone trying this.

**Comment by sfinn-qci** [comment]
The NuGet is located [here](https://github.com/Microsoft/ApplicationInsights-Xamarin/tree/master/ApplicationInsightsXamarinSDK/ApplicationInsightsXamarin/NuGet)

Instructions on how to import them into Visual Studio can be found [here](https://docs.nuget.org/create/hosting-your-own-nuget-feeds)

**Comment by jmichas** [comment]
Ok, thank you, I will try that.

**Comment by ghost** [comment]
Wait guys, you are talking about two different things. @sfinn-qci is referencing the Nupkg in the current Master and @jmichas has issues with the one of the "no forms dependency" branch ([see this PR](https://github.com/Microsoft/ApplicationInsights-Xamarin/pull/12)). Also please send me some details about the Xamarin/IDE versions you are using. Thanks

**Comment by jmichas** [comment]
Yeah, I was trying to get it to work with forms, so actually using the develop branch nugets worked finally.
I forget exactly why I was trying to use the no forms versions, I think it was something I read in an issue, maybe that there was a hard dependency on XF 1.4 and I am using the latest 2.1(?) I think. So, the master nugets didnnt install in the PCL but the develop branch did.

**Comment by ghost** [comment]
@jmichas: You can find a new nupkg [here](https://github.com/Microsoft/ApplicationInsights-Xamarin/tree/master/ApplicationInsightsXamarinSDK/NuGet)
