### ISSUE TITLE
How to use StartNewSession and SetUserId?

### ISSUE THREAD

**Issue by jmichas** [Microsoft/ApplicationInsights-Xamarin#22]
Do we use StartNewSession() in place of Start()? 
And can SetUserId() be called at any time or does it need to be called before Start()? 
Also, how do we get authenticated users to show up in the AI dashboard as explained in the JS version here https://azure.microsoft.com/en-us/documentation/articles/app-insights-web-track-usage/  (see authenticated users section). Is this possible in the Xam platform version?

Thanks.

**Comment by ghost** [comment]
Hi @jmichas,

`StartNewSession()` is not a replacement for the `Start()` call. You  use `StartNewSession()` to renew the session ID manually. 

Calling `SetUserId()` can be done even after calling start. However, this will only update the anonymous user ID. Setting the ID of an authenticated user is not supported by the SDK.

Regards
