### ISSUE TITLE
Missing nupkg file in release v1.0 alpha 3

### ISSUE THREAD

**Issue by cookmedic** [Microsoft/ApplicationInsights-Xamarin#24]
The Microsoft.ApplicationInsights.Xamarin.1.0.0-alpha3.nupkg file is missing from the ApplicationInsightsXamarinSDK\NuGet folder thus preventing installation from NuGet.

**Comment by ghost** [comment]
You can find the nupkg [here](https://github.com/Microsoft/ApplicationInsights-Xamarin/tree/master/ApplicationInsightsXamarinSDK/NuGet)
