### ISSUE TITLE
About Exception reporting APIs

### ISSUE THREAD

**Issue by akamud** [Microsoft/ApplicationInsights-Xamarin#26]
I noticed the last versions of Application Inisghts removed support for exceptions reporting in favor to HockeyApp. The problem is that HockeyApp for Xamarin still doesn't support (known) exception reporting, only crashes.

So right now users don't have a way of doing that, since everyone (Xamarin Insights and AppInsights) is dropping support and telling us to use a feature that isn't available yet on HockeyApp SDK for Xamarin.

What is the recommended way for doing this now? Would Application Insights consider putting back the exception APIs until HockeyApp releases a more complete version of the SDK for Xamarin?

**Comment by ghost** [comment]
These ApplicationInsights SDKs are not maintained any longer. We are working on adding support for handled Exceptions to HockeyApp, but we don't have an ETA at this moment.

**Comment by akamud** [comment]
Since there is no ETA, could Application Insights put this back until it is available on HockeyApp?

**Comment by ghost** [comment]
To my knowledge Application Insights has no plans on supporting mobile apps besides this: https://azure.microsoft.com/en-us/blog/access-hockeyapp-data-in-ai-with-hockeyapp-bridge-app/
