### ISSUE TITLE
1.0-alpha3 does not build on Xamarin.Forms 2.3.2.127

### ISSUE THREAD

**Issue by akamud** [Microsoft/ApplicationInsights-Xamarin#27]
When creating a new project with Xamarin.Forms 2.3.2.127, as soon as you add Application Insights alpha3 the Android project just breaks and won't build anymore. If you remove Application Insights you can build the project successfully again.
I tested this with the local NuGet package.

All the errors are related to `Resource.designer.cs` file, like this one:

```
CS0117    'Resource.Styleable' does not contain a definition for 'Theme_actionBarSplitStyle'    demo_xamarin.Droid    C:\Users\x\Documents\Pessoal\Xamarin_Projects\demo_xamarin\demo_xamarin\demo_xamarin.Droid\Resources\Resource.Designer.cs
```

There are more than 150 errors, all related to this file. 

I've tried many, many things, until I suspected the problem was the Insights package.

Does Application Insights work with Forms newer than 2.0.1.6505?

If that's the case, I think this should be more explicit on the README:
```
Furthermore, the SDK has a dependency on 2.0.1.6505
```
does not seem very clear to me. Newcomers might not understand you are talking about Forms version, and might assume this is a minimum dependency, and not hard dependency.

**Comment by lumaxis** [comment]
@akamud Unfortunately, Application Insights does not support Xamarin anymore and this SDK is deprecated and will not be maintained by us anymore, as explained in our Readme: https://github.com/Microsoft/ApplicationInsights-Xamarin#breaking-changes
