### ISSUE TITLE
Upload dsym file

### ISSUE THREAD

**Issue by dominik-weber** [Microsoft/ApplicationInsights-Xamarin#3]
Is there a way to upload the dsym file to Application Insights? Currently my crash stack traces are not very informative and I think this results from the fact that the system doesn't have the dsym available.

The following stack trace is shown in Application Insights:
SIGTRAP
libdyld.dylib
MobileClient.IOS
MobileClient.IOS
MobileClient.IOS
MobileClient.IOS
MobileClient.IOS
MobileClient.IOS
MobileClient.IOS
???
???
???
???
[...]

**Comment by ghost** [comment]
You can upload your symbols with the Application Insights for Mac application which you can download here: https://azure.microsoft.com/en-us/documentation/articles/app-insights-ios/

**Comment by ullstrm** [comment]
I'm having problems with uploading the dsym aswell. The archive built from Xamarin Studio is flagged as "Component Missing!" in the "Application Insights"-mac app. How would one solve this?

**Comment by dominik-weber** [comment]
@spoek I found out that you have to include the key in the Info.plist file to make the upload tool work:

> Open the Info.plist of your app target and add a new field of type String. Name it MSAIInstrumentationKey and set your Application Insights instrumentation key from 4.1 as its value.

**Comment by ghost** [comment]
If you set the instrumentation key via code, the Mac application can not find the iKey. But you can use the context menu (right mouse click) in the Mac app on the archive to assign the corresponding app on AI manually.

**Comment by lumaxis** [comment]
@padinger Should we add some more information for this case? Either in the Mac app or in our general documentation?

**Comment by ghost** [comment]
@lukasspiess I think setting the iKey via plist is already the default case that is documented in the docu. But we should come up with some documentation for the AI OSX app in the future probably.

**Comment by lumaxis** [comment]
Setting the Instrumentation Key via the `Info.plist` file solves this. Closing this for now although we will work on a better error message and better documentation in the future.

**Comment by nstublen** [comment]
Is there a way to include uploading of the DSYM file as part of an automated build process?

**Comment by chrwend** [comment]
Just install and run Application Insights for OSX before you build. You'll get a notification after the build has been finished. Click on its "upload" button to upload the app binary as well as the DSYM.
