### ISSUE TITLE
Reuse de PCL implementation instead of a new one

### ISSUE THREAD

**Issue by Savanete** [Microsoft/ApplicationInsights-Xamarin#4]
Hi,

I have recompiled the PCL implementation for dotnet adding targets for Xamarin and it works. Why a new implementation is required instead of creating extensions for iOS and Android?

Thanks!

**Comment by ghost** [comment]
Because iOS & Android crashes need to be processed differently. E.g. on iOS we have to use a certain library to provide you with meaningful crash information.
