### ISSUE TITLE
Why is Xamarin.Forms a dependency?

### ISSUE THREAD

**Issue by Cheesebaron** [Microsoft/ApplicationInsights-Xamarin#7]
I wan't to add ApplicationInsights to a Xamarin.iOS project which does **not** use Xamarin.Forms. I do **not** want to pull in Xamarin.Forms in as a dependency. I don't see a need for this.

**Comment by ghost** [comment]
We are already aware of this issue and currently thinking about using the bait and switch approach instead. Unfortunately, there is no ETA for that at this point.

**Comment by Cheesebaron** [comment]
Where are you doing your development? You are only pushing commits to github when you feel like it? Would be nice to see more frequent commits.

If Xamarin.Forms is only used for injecting, how come you did not consider any of the other IoC libraries out there instead of pulling in something that contains so much else? It just seems like it was not thought very well through.

I look forward to trying it out when the dependency on Xamarin.Forms has been removed, until then I will use something else.

**Comment by ghost** [comment]
Thanks for your feedback, I'm going to get back to you once we removed the dependency.

**Comment by dbohls** [comment]
I want to chime in that I also cannot consider Application Insights until the Xamarin.Forms dependency is removed. It puts our app too close to the 60 MB/slice limit.

**Comment by ghost** [comment]
I'm sorry to hear that. Have you ever thought of switching to HockeyApp? It also comes with a Xamarin SDK: hockeyapp.net.

-Christoph

Von Outlookhttp://aka.ms/Ox5hz3 gesendet

On Sat, Oct 10, 2015 at 9:55 PM -0700, "dbohls" <notifications@github.com<mailto:notifications@github.com>> wrote:

I want to chime in that I also cannot consider Application Insights until the Xamarin.Forms dependency is removed. It puts our app too close to the 60 MB/slice limit.

##

**Comment by dbohls** [comment]
Unless HockeyApp has added event tracking, it's not an option either.
