### ISSUE TITLE
Profile49

### ISSUE THREAD

**Issue by durandt** [Microsoft/ApplicationInsights-Xamarin#8]
Hi, 

I can see that `AI.XamarinSDK.Abstractions.csproj` targets Profile49. 
Is there any reasons why the SDK can't support WPA81 and Windows platforms, and use profile 78 or 259 instead?

Regards,

**Comment by ghost** [comment]
Can you please switch to the following branch and give it another try? [change-pcl-profile](https://github.com/Microsoft/ApplicationInsights-Xamarin/blob/feature/change-pcl-profile/ApplicationInsightsXamarinSDK/ApplicationInsightsXamarin/AI.XamarinSDK.Abstractions/AI.XamarinSDK.Abstractions.csproj)

**Comment by durandt** [comment]
It did the trick, thanks!
