### ISSUE TITLE
Crash reports are created and sent but don't show up in Azure's portal (iOS)

### ISSUE THREAD

**Issue by durandt** [Microsoft/ApplicationInsights-Xamarin#9]
Hi, 

I created an _Application Insights_ resource in Azure's portal (`ApplicationType="iOS Application"`). 
Using the provided instrumentation key, I initialized `ApplicationInsights` as described in the readme. 

I do get some telemetry in the Azure web portal (Users, sessions, page views) but I don't get any crash report. 

I crash with a simple `NullReferenceException` when I click a button: 

```
string name = null;
int i = name.Length;
```

The app does crash and I can see that a report is created in the simulator's filesystem at: 
`Library/Application Support/com.microsoft.ApplicationInsights/highPrio`

When I start the application then the report disappears (I guess it is sent to Azure) but never shows up in the statistics in the web portal. 
I get either "0 crashes":
![skarmavbild 2015-09-21 kl 15 48 05](https://cloud.githubusercontent.com/assets/1219650/9993578/d9bb346c-6078-11e5-89e8-c759b973803b.png)
... or a message mentioning that I have to configure crash reporting: 
![skarmavbild 2015-09-21 kl 15 30 58](https://cloud.githubusercontent.com/assets/1219650/9993584/dceacda0-6078-11e5-9010-a9e857486f7a.png)

The read.me file does not mention anything about crash reporting configuration, it says it is enabled by default. 

Did I miss something? 

Furthermore, the app seems to freeze instead of crashing the second time I make the crash occur. 

Regards,

---

Xamarin Studio Version 5.9.5 (build 9)
Xcode 6.4 (7720) Build 6E35b
Xamarin.iOS Version: 8.10.4.46 (Business Edition)
Xamarin.Android Version: 5.1.5.3 (Business Edition)
Mac OS X 10.10.5

**Comment by ghost** [comment]
Hi,

thanks for reporting that issue. I assume that neccessary assemblies get stripped. Can you please provide me with the complete stacktrace. 

In the meanwhile, please try to add `AI.XamarinSDK.iOS.ApplicationInsights.Init();` inside your `FinsihedLaunching()` of your `AppDelegate.cs`.

**Comment by durandt** [comment]
Hi @chrwend,

This is the code I have in my `FinishedLaunching(app, options)` method:

```
AI.XamarinSDK.iOS.ApplicationInsights.Init();
ApplicationInsights.Setup("my instrumentation key");
ApplicationInsights.SetDebugLogEnabled(true);
ApplicationInsights.Start();
```

So I do already call the Init() method as specified in the read.me

Not sure which stacktrace you are asking for (the fake crash or the freeze). I will attach the file generated by Application Insights (the one that vanishes) that contains the NullReferenceException stacktrace. 
I could not reproduce the freeze issue today, so I cannot give a stack trace for that one. 

Since I have enabled `DebugLog` I can now see that crash reports are successfully sent by MSAI. 
However, I sometimes see this error message when MSAI sends usage data: 

```
message = "Property: data is not provided"
```

Please tell me if I did not give you the expected information or if you need more information. 
Regards, 

(There's no way to attach text files so here are two crash reports that were sent to AI but don't show up in the web interface)
(Note: I have obfuscated appId and iKey)

---

Crash with release build on simulator: 

```
{
    "appId": "obfuscated",
    "appVer": "1.0 (1.0)",
    "data": {
        "baseData": {
            "exceptions": [
                {
                    "hasFullStack": "true",
                    "message": "Object reference not set to an instance of an object",
                    "parsedStack": [
                        {
                            "fileName": "<filename unknown>",
                            "level": 7,
                            "method": "LiuApp.Core.Presentation.HomePage.<LoadView>m__0 (System.Object sender, System.EventArgs e)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 6,
                            "method": "Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked ()"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 5,
                            "method": "Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 4,
                            "method": "UIKit.UIControlEventProxy.Activated ()"
                        },
                        {
                            "level": 3,
                            "method": "(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 2,
                            "method": "UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 1,
                            "method": "UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 0,
                            "method": "LiuApp.iOS.Application.Main (System.String[] args)"
                        }
                    ],
                    "stack": "  at LiuApp.Core.Presentation.HomePage.<LoadView>m__0 (System.Object sender, System.EventArgs e) [0x00000] in <filename unknown>:0 \n  at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () [0x00000] in <filename unknown>:0 \n  at Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs) [0x00000] in <filename unknown>:0 \n  at UIKit.UIControlEventProxy.Activated () [0x00000] in <filename unknown>:0 \n  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate) [0x00000] in <filename unknown>:0 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00000] in <filename unknown>:0 \n  at LiuApp.iOS.Application.Main (System.String[] args) [0x00000] in <filename unknown>:0 ",
                    "typeName": "NullReferenceException"
                }
            ],
            "handledAt": "UNHANDLED",
            "measurements": {},
            "properties": {},
            "severityLevel": 0,
            "ver": 2
        },
        "baseType": "ExceptionData"
    },
    "deviceId": "D7F555CF-8AAE-4625-8B45-D864CDB3BCEE",
    "iKey": "cdba1ad0-3247-4952-9095-xxxxxxxxxxxx",
    "name": "Microsoft.ApplicationInsights.Exception",
    "os": "iPhone OS",
    "osVer": "8.4 (14F27)",
    "sampleRate": 100,
    "tags": {
        "ai.application.ver": "1.0 (1.0)",
        "ai.device.id": "D7F555CF-8AAE-4625-8B45-D864CDB3BCEE",
        "ai.device.language": "sv",
        "ai.device.locale": "sv_US",
        "ai.device.model": "x86_64",
        "ai.device.network": "WIFI",
        "ai.device.oemName": "Apple",
        "ai.device.os": "iPhone OS",
        "ai.device.osVersion": "8.4 (14F27)",
        "ai.device.screenResolution": "1136x640",
        "ai.device.type": "Phone",
        "ai.internal.sdkVersion": "ios:1.0-beta.4",
        "ai.session.id": "887CCA57-5F2F-4569-81FF-70BB66D38FBB",
        "ai.session.isFirst": "false",
        "ai.session.isNew": "false",
        "ai.user.id": "D7F555CF-8AAE-4625-8B45-D864CDB3BCEE"
    },
    "time": "2015-09-23T11:14:15.773Z",
    "ver": 1
}
```

---

Crash with debug build on iPhone 5s: 

```
{
    "appId": "obfuscated",
    "appVer": "1.0 (1.0)",
    "data": {
        "baseData": {
            "exceptions": [
                {
                    "hasFullStack": "true",
                    "message": "Object reference not set to an instance of an object",
                    "parsedStack": [
                        {
                            "fileName": "$HOME/projects/xamarin/LiUapp/LiuApp/LiuApp.Core/Presentation/Pages/DetailPages/HomePage.cs",
                            "level": 7,
                            "line": 36,
                            "method": "LiuApp.Core.Presentation.HomePage.<LoadView>m__0 (System.Object sender, System.EventArgs e)"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 6,
                            "method": "Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked ()"
                        },
                        {
                            "fileName": "<filename unknown>",
                            "level": 5,
                            "method": "Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs)"
                        },
                        {
                            "fileName": "/Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIControl.cs",
                            "level": 4,
                            "line": 34,
                            "method": "UIKit.UIControlEventProxy.Activated ()"
                        },
                        {
                            "level": 3,
                            "method": "(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)"
                        },
                        {
                            "fileName": "/Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIApplication.cs",
                            "level": 2,
                            "line": 74,
                            "method": "UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate)"
                        },
                        {
                            "fileName": "/Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIApplication.cs",
                            "level": 1,
                            "line": 57,
                            "method": "UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)"
                        },
                        {
                            "fileName": "$HOME/projects/xamarin/LiUapp/LiuApp/iOS/Main.cs",
                            "level": 0,
                            "line": 17,
                            "method": "LiuApp.iOS.Application.Main (System.String[] args)"
                        }
                    ],
                    "stack": "  at LiuApp.Core.Presentation.HomePage.<LoadView>m__0 (System.Object sender, System.EventArgs e) [0x00004] in $HOME/projects/xamarin/LiUapp/LiuApp/LiuApp.Core/Presentation/Pages/DetailPages/HomePage.cs:36 \n  at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () [0x00020] in <filename unknown>:0 \n  at Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs) [0x0000e] in <filename unknown>:0 \n  at UIKit.UIControlEventProxy.Activated () [0x00007] in /Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIControl.cs:34 \n  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate) [0x00005] in /Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIApplication.cs:74 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0001c] in /Users/builder/data/lanes/2077/d8e9592a/source/maccore/src/UIKit/UIApplication.cs:57 \n  at LiuApp.iOS.Application.Main (System.String[] args) [0x00008] in $HOME/projects/xamarin/LiUapp/LiuApp/iOS/Main.cs:17 ",
                    "typeName": "NullReferenceException"
                }
            ],
            "handledAt": "UNHANDLED",
            "measurements": {},
            "properties": {},
            "severityLevel": 0,
            "ver": 2
        },
        "baseType": "ExceptionData"
    },
    "deviceId": "54C01692-9BE2-4FBE-831F-B7672C8580E1",
    "iKey": "cdba1ad0-3247-4952-9095-xxxxxxxxxxxx",
    "name": "Microsoft.ApplicationInsights.Exception",
    "os": "iPhone OS",
    "osVer": "8.4.1 (12H321)",
    "sampleRate": 100,
    "tags": {
        "ai.application.ver": "1.0 (1.0)",
        "ai.device.id": "54C01692-9BE2-4FBE-831F-B7672C8580E1",
        "ai.device.language": "sv",
        "ai.device.locale": "sv_SE",
        "ai.device.model": "iPhone6,2",
        "ai.device.network": "WIFI",
        "ai.device.oemName": "Apple",
        "ai.device.os": "iPhone OS",
        "ai.device.osVersion": "8.4.1 (12H321)",
        "ai.device.screenResolution": "1136x640",
        "ai.device.type": "Phone",
        "ai.internal.sdkVersion": "ios:1.0-beta.4",
        "ai.session.id": "14451035-4B37-48B6-887B-4F9EDF102343",
        "ai.session.isFirst": "true",
        "ai.session.isNew": "false",
        "ai.user.id": "54C01692-9BE2-4FBE-831F-B7672C8580E1"
    },
    "time": "2015-09-23T11:32:21.137Z",
    "ver": 1
}
```

**Comment by ghost** [comment]
Sorry for responding late. The assembly gets stripped. Unfortunately I can't reproduce this issue. Can you provide me with your demo app?

Thank you

**Comment by durandt** [comment]
Sure. I'll do that early tomorrow (European time). 
Is there any way I can send it to you without exposing my instrumentation key? or should I just remove it?

Regards,

**Comment by ghost** [comment]
Just replace it with a placeholder. Thank you.

**Comment by durandt** [comment]
Hi,

I have tried with Android too now and I get the same symptoms, which are: 
1. In Azure portal, there is an overlay "Learn how to collect crash data."
2. I crash my app
3. I can see on the file system that a file is created in the "high prio" queue
4. I restart the app
5. The crash report is sent and the file is removed from the "high prio" queue
6. In Azure portal, the overlay disappeared and shows a graph which zero (0) crashes. 

Point 3 though, if I compare the JSON och the crash reports generated on iOS and Android i can see that the JSON object i pasted above is wrapped into a list on Android: 
iOS : `{ ... payload ... }`
Android : `[{ ... payload ... }]`
But it's likely insignificant. 

In Azure's portal, I created both an "iOS" and an "Android" insight projects, is that the right way to do even for Xamarin.Forms applications? I could not se another category that would really fit. 

Also, I think the §4.3 point 3 of the readme is a little bit confusing. I have a Xamarin.Forms application that targets both Android and iOS, should I put the initialization code both in AppDelegate, MainActivity and the Xamarin.Forms Application class? I had it first only in AppDelegate (iOS) and MainActivity (Android), but I have tried all combinations and did not get any difference in behavior regarding crash reporting. 

I created a sample project that I uploaded here:
https://github.com/durandt/AppInsightsTest

As written in issue #11, I use Xamarin Studio 5.9.7 on Mac OS X 10.10.5 and I use the feature/change-pcl-profile branch. 

This is how I use it in my "real" project and I get exactly the same issue: Crash reports are sent but don't show up in Azure's portal. 

Regards,

**Comment by ghost** [comment]
I'll give it a try.

In the meanwhile, can you tell me:
- Which browser are you using?
- Don't be confused by the different JSON formats of the request. The backend can handle both types.
- I prefer to create separate apps in the Azure Portal for every supported platform. It's possible to create an iOS app which gets data from my Xamarin iOS and Android app. This will work fine for telemetry data such as events or page data, but not for crashes.

Thank you!

**Comment by ghost** [comment]
Hi,

I just checked your test app and it sends out exceptions as well as telemetry data without changing anything in code (besides the iKey).

The reason why it won't show app in the crashes chart is that we are sending out a custom data type. The backend is not able to recognise those as "crash". To see the exceptions you can click on the "search" tile.

Thank you

**Comment by durandt** [comment]
Hi. 

I use Chrome 45.0.2454.101 on Mac OS X. 
I did think that the issue may have to do with the fact that Xamarin.iOS apps are a bit different from native iOS apps. I am rather new to the Azure portal otherwise I think I would have searched for the events. 
Thank you for the tips!

No we are getting out of scope for this issue/repository but: 
- Do you know if there is any plan to "fix" this? 
- Do you know if there is any plan to "group" crashes and exception?

Second point is, because after I've been a bad programmer and shipped an app with multiple crashes, linear searching for new crashes is very hard when the time-line is flooded with old ones. 

Thank you for your help.

**Comment by ghost** [comment]
Hey,

unfortunately, there's no ETA for the features/bugs above. If your main interest is crash reporting, I highly recommend using HockeyApp. It's the best mobile crash reporting service on the market. It also comes with a [Xamarin SDK](http://hockeyapp.net/releases/).
